# $Id: Makefile,v 1.6 2012/06/26 06:09:52 stefano Exp $

lcpc:
	cd cpc ; $(MAKE) ; cd ..

losca:
	cd osca ; $(MAKE) ; cd ..

lzx:
	cd spectrum ; $(MAKE) ; cd ..

lz88:
	cd z88 ; $(MAKE) ; cd ..

clean:
	cd cpc ; $(MAKE) clean ; cd ..
	cd z88 ; $(MAKE) clean ; cd ..
	cd spectrum ; $(MAKE) clean ; cd ..
	cd osca ; $(MAKE) clean ; cd ..
