.TH sock_puts 3z "18 February 2000" ""  "z88dk Programmer's Manual"
.SH NAME
sock_write \- write string to a network socket
.SH SYNOPSIS
.nf
.B #include <net/socket.h>
.sp
.BI "size_t sock_puts(SOCKET *"s ", char *"dp );
.fi
.SH DESCRIPTION
The parameter \fIs\fP is a descriptor to an open socket created using
\fBsock_open(3z)\fP or \fBsock_listen(3z)\fP
.PP
The \fBsock_puts()\fP function writes the NULL terminated string \fIdp\fP
to the socket specified by \fIs\fP.


.SH "RETURN VALUE"
The \fBsock_write()\fP function returns the number of bytes written
to the socket. If an illegal socket is supplied the carry
flag will be set and the return value will be EPROTONOSUPPORT.


.SH "SEE ALSO"
.BR sock_write "(3z), " sock_putc (3z)

.SH AUTHOR
Dominic Morris <dom@jb.man.ac.uk>
