.TH sock_close 3z "18 February 2000" ""  "z88dk Programmer's Manual"
.SH NAME
sock_close \- close a network connection
.SH SYNOPSIS
.nf
.B #include <net/socket.h>
.sp
.BI "void sock_close(SOCKET *"s);
.fi
.SH DESCRIPTION
The parameter \fIs\fP is a descriptor to an open socket created using
\fBsock_open(3z)\fP or \fBsock_listen(3z)\fP. 
.PP
The \fBsock_close()\fP function will initiate a close on the socket
specified by \fIs\fP. Once this function has been called no more data
can be written to the socket. If the socket is of type prot_TCP then
data can continue to be read.


.SH "RETURN VALUE"
None

.SH "SEE ALSO"
.BR sock_abort "(3z), " sock_shutdown "(3z)"

.SH AUTHOR
Dominic Morris <dom@jb.man.ac.uk>

