#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.1 2007/05/17 16:25:53 stefano Exp $

all:
	@echo ''
	@echo 'Nowt todo here (clock is asm)'
	@echo ''
	@echo ''

clean:
	$(RM) *.o* *.i *.sym *.map zcc_opt.def
