#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.9 2008/07/21 10:09:26 stefano Exp $

all:
	@echo ''
	$(RM) strlcat_callee.o
	$(RM) strlcpy_callee.o
	$(RM) strlen.o

clean:
	$(RM) *.o* *.sym *.map zcc_opt.def
