#
# Makefile for platform specific input routines
#
# $Id: Makefile,v 1.4 2015/08/05 07:24:24 pauloscustodio Exp $

include ../Make.config

clean:
	$(RM) spectrum/*.o*
	$(RM) zx81/*.o*
	$(RM) x1/*.o*
