#
# Makefile for ZX 81 target specific lib
#
# $Id: Makefile,v 1.3 2012/04/18 10:17:13 stefano Exp $

include ../Make.config


all:
	@echo ''


clean:
	$(RM) *.o* basic/*.o* tape/*.o* *.sym *.map zcc_opt.def
