# Z88DK Z80 Macro Assembler
#
# Copyright (C) Gunther Strube, InterLogic 1993-99
# Copyright (C) Paulo Custodio, 2011-2015
# License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
# Repository: https://github.com/pauloscustodio/z88dk-z80asm

#.SUFFIXES: .txt .html
#
#SRCS 	:= $(wildcard *.txt)
#HTMLS	:= $(SRCS:.txt=.html)
#
#.txt.html:
#	perl mmd2html.pl $<
#
#all: 	$(HTMLS)
#
#$(HTMLS) : mmd2html.pl

# User manual source in Google Docs and published as
# https://docs.google.com/document/d/1BDmDaQKLT_538uPrsFTlDM-ChLSlaGcqaEVs8Px9ac0/pub
# Converted to txt by reformat_html.pl

all:	z80asm.txt

z80asm.txt : z80asm.html reformat_html.pl
	perl reformat_html.pl z80asm.html
