// command ids for comm protocol between c64 and pi

#define COMMAND_USER_INPUT 10
#define COMMAND_GET_STATUS 11
#define COMMAND_GET_FRAME 12
#define COMMAND_GET_FRAME_LEFT 13
#define COMMAND_GET_FRAME_RIGHT 14
#define COMMAND_GET_FRAME_UP 15
#define COMMAND_GET_FRAME_DOWN 16
#define COMMAND_GET_FRAME_RESET 17
