
// automatically generated by m4 from headers in proto subdir


#ifndef _LIMITS_H
#define _LIMITS_H

#define CHAR_BIT       8

#define SCHAR_MIN     -128
#define SCHAR_MAX      127
#define UCHAR_MAX      255U

#define SHRT_MIN      -32768
#define SHRT_MAX       32767
#define USHRT_MAX      65535U

#define INT_MIN       -32768
#define INT_MAX        32767
#define UINT_MAX       65535U

#define LONG_MIN      -2147483648L
#define LONG_MAX       2147483647L
#define ULONG_MAX      4294967295UL

#endif
