#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.3 2002/10/22 19:15:24 dom Exp $

all:
	@echo ''
	@echo 'Nowt todo here (clock is asm)'
	@echo ''
	@echo ''

clean:
	$(RM) *.o* *.i *.sym *.map zcc_opt.def
