;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_test

; ---------------------------------------------------------------
; void __near__ test (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test: near

.segment	"CODE"

	ldx     #$00
	lda     $DD02
	jsr     pusha
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	ora     #$04
	ldy     #$00
	sta     (sp),y
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $DD02
	ldx     #$00
	lda     #$00
	sta     $04A0
	ldx     #$00
	lda     #$00
	sta     $D8A0
	jsr     incsp1
	rts

.endproc

