.TH BOGOMIPS 1 "4 Jun 1994" "Linux" "User Commands"
.SH NAME
bogomips \- BogoMIPs Benchmark Program
.SH SYNOPSIS

bogomips

.SH DESCRIPTION

.B Bogomips
is a standalone version of the benchmark program run by the Linux
kernel at boot time.

.PP
.SH "COMMAND\-LINE OPTIONS"

No options are currently supported.

.SH EXAMPLES
.TP 0.5i
.B bogomips

.SH PORTABILITY
.B Bogomips
should compile on any ANSI C conforming system.

.SH BUGS/LIMITATIONS
.PP
The "Bogo" in BogoMIPs stands for bogus. See the BOGOMips Mini-HOWTO
document for more information on interpreting the results of the
program. See also the "New Hacker's Dictionary" (sometimes known as the
"Jargon File") for a definition of bogosity and bogon particle
physics.

.SH AUTHOR
.B Bogomips
was written by Jeff Tranter (Jeff_Tranter@Mitel.COM) based on code
from the Linux kernel, by Linus Torvalds. Additional changes suggested
by Thomas McWilliams and Paul Healy.
